// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonasAPI.Infrastructure.Db;

#nullable disable

namespace PersonasAPI.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20221221230617_computedColumn")]
    partial class computedColumn
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PersonasAPI.Model.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Categoria")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(max)")
                        .HasComputedColumnSql("CASE\r\n	WHEN FLOOR(DATEDIFF(DAY, FechaNacimiento, GETDATE())/365.25) < 11 THEN 'Niños' 	\r\n	WHEN FLOOR(DATEDIFF(DAY, FechaNacimiento, GETDATE())/365.25) >=11 AND FLOOR(DATEDIFF(DAY, FechaNacimiento, GETDATE())/365.25) < 18 THEN 'Adolescentes'\r\n	WHEN FLOOR(DATEDIFF(DAY, FechaNacimiento, GETDATE())/365.25)>=18 AND FLOOR(DATEDIFF(DAY, FechaNacimiento, GETDATE())/365.25) < 80 THEN 'Adultos'\r\n	WHEN FLOOR(DATEDIFF(DAY, FechaNacimiento, GETDATE())/365.25) >=80 THEN 'Octogenario'\r\nEND ");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persona");
                });
#pragma warning restore 612, 618
        }
    }
}
